media:
  input: assets/images      # 图片在仓库里实际存放的文件夹
  output: /assets/images    # 文章里引用图片时用的网址路径（带开头的斜杠）

content:
  - name: posts
    label: 今日所念
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{fields.title}.md"
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true
      - name: date
        label: 发布时间
        type: date
        required: true
        options:
          time: true
          format: "yyyy-MM-dd HH:mm:ss"
      - name: body
        label: 正文内容
        type: rich-text
