media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: 今日所念
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{fields.title}.md"
    view:
      fields: [title, category, date]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true
      - name: category
        label: 分类
        type: select
        required: true
        options:
          values: ["今日所念", "学习", "阅读＆观影", "旅行"]
      - name: date
        label: 发布时间
        type: date
        required: true
        options:
          time: true
          format: "yyyy-MM-dd HH:mm:ss"
      - name: body
        label: 正文内容
        type: rich-text
